### ISSUE TITLE
Need new maintainer?

### ISSUE THREAD

**Issue by nsonnad** [tmcw/react-tangle#13]
Curious whether mapbox has moved to a different solution for this, ie, if there's a similar project that is still maintained.

If there isn't, [Quartz](https://github.com/Quartz) would be happy to take over `react-tangle` which we are still using

**Comment by tmcw** [comment]
That'd be great! We developed react-tangle as part of Mapbox Studio, but moved away from it - it was great for interactive tweaking but cartographers preferred typing :) Happy to transfer & npm owner add - who to?

**Comment by nsonnad** [comment]
sounds good, https://www.npmjs.com/~quartz works

**Comment by tmcw** [comment]
:+1: npm owner add'ed. i can't transfer this repo yet since quartz has a fork already

**Comment by nsonnad** [comment]
Ok cool, thanks. If you can accept #14 i will delete our fork and you can transfer. Sorry for the trouble

**Comment by nsonnad** [comment]
(deleted (the fork, that is))

**Comment by tmcw** [comment]
Github's repo transfers have gotten stricter! Okay, so since [transferring to Quartz isn't possible for me](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization), I'll transfer it to you @nsonnad and you'll _then_ transfer it to Quartz, sound like a plan?

**Comment by nsonnad** [comment]
Ah damn, yeah that works

**Comment by tmcw** [comment]
Okay - you also have a fork of this project :)

**Comment by nsonnad** [comment]
Ha oh man, deleted

**Comment by tmcw** [comment]
Cool, requested a transfer to your account

**Comment by tmcw** [comment]
Transfer is still available, but not taken so far. Closing.
