### ISSUE TITLE
React-Redux compatibility

### ISSUE THREAD

**Issue by cannc4** [tmcw/react-tangle#17]
Hi, just curious if it's still supported as I am getting the error 

`Error in ./~/react-knob/index.js
Module parse failed: /Users/canince/Documents/Github/sq/node_modules/react-tangle/index.js Unexpected token (34:6)
You may need an appropriate loader to handle this file type.
`
I'd appreciate any help
Thanks

**Comment by tmcw** [comment]
This error doesn't mention this module. Perhaps you have the wrong repo?

**Comment by cannc4** [comment]
got it fixed now, thanks
