### ISSUE TITLE
increment with scrollwheel?

### ISSUE THREAD

**Issue by ajashton** [tmcw/react-tangle#9]
I find the click & drag approach to adjusting numbers a little awkward & unpredictable. It takes more work than it should to get to the number I want. I really like the interaction of native numerical fields (at least with GTK or Qt apps) where i can just hover my mouse over the field and scroll up or down to increment the value. This also works for dropdown menus and tab bars, so I've gotten pretty used to the pattern. Would it be possible to have this work in react-tangle as well?

**Comment by tmcw** [comment]
Hm, potentially. Problem is really that mouseWheel values, as you've noticed on the 'zooming the map' note, are wildly non-standard and even the most time-tested approaches to trying to make them similar between mac/windows/linux/mice/touchpads/marble balls/minorityreportpanelinterfaces are pretty janky.

Fwiw, I have a feeling that any custom input anywhere will provide wildly disparate opinions from everyone everywhere, much as we've found with all custom inputs thus far.

**Comment by tmcw** [comment]
This was implemented as react-tangle-compat earlier this month: https://github.com/mapbox/react-tangle-compat/commit/968b1bab0b992466993a91c70075b2d6462a055d
